#!/bin/bash

#SBATCH --account BIOENG-455
#SBATCH --reservation bioeng-455
#SBATCH --job-name="my-job-name"
#SBATCH --qos=normal
#SBATCH --nodes 1
#SBATCH --ntasks-per-core 1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu 1024
#SBATCH --time 24:00:00
#SBATCH --output out-%J.txt
#SBATCH --error err-%J.txt


 odpd-fidis  001&
wait
